export const GET_BASKET_SUCCESS="GET_BASKET_SUCCESS"
export const BASKET_REQUEST="BASKET_REQUEST"
export const BASKET_FAILURE="BASKET_FAILURE"

export const USER_LOADING = "USER_LOADING"
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS"
export const USER_SIGNUP_SUCCESS = "USER_SIGNUP_SUCCESS"
export const USER_FORGOT_SUCCESS = "USER_FORGOT_SUCCESS"
export const USER_RESET_SUCCESS = "USER_RESET_SUCCESS"
export const USER_FAIL = "USER_FAIL"
export const VALID_USER_LOGOUT_SUCCESS = "VALID_USER_LOGOUT_SUCCESS"


export const GET_CLIENTS_SUCCESS="GET_CLIENTS_SUCCESS"
export const GET_ALGO_CLIENTS_SUCCESS="GET_ALGO_CLIENTS_SUCCESS"
export const CLIENTS_REQUEST="CLIENTS_REQUEST"
export const CLIENTS_FAILURE="CLIENTS_FAILURE"